### ISSUE TITLE
Failed to activate the css-comb package

### ISSUE THREAD

**Issue by charliegroll** [d4rkr00t/css-comb-atom#13] opened 2015-10-17 02:11 UTC
[Enter steps to reproduce below:]
1. Try updating

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [css-comb](https://github.com/d4rkr00t/css-comb-atom) package, v2.4.0
### Stack Trace

Failed to activate the css-comb package

```
At object is not a function

TypeError: object is not a function
    at Object.activate (/Users/charlie/.atom/packages/css-comb/lib/main.js:51:21)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:245:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:226:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:169:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:218:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:486:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:313:60
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:60:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```
### Commands

```
     -2:43.3.0 core:redo (atom-text-editor.editor.is-focused)
  2x -2:42.5.0 core:undo (atom-text-editor.editor.is-focused)
     -2:29.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:25 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:21.7.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  2x -2:20.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:31 editor:newline (atom-text-editor.editor.is-focused)
  9x -1:24.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:05.1.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -1:02.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:43.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:37.6.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:35.9.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:35.5.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:33.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:29.4.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.13
css-comb, v2.4.0

# Dev
No dev packages
```

**Comment by d4rkr00t** [comment] 2015-10-17 06:44
Wow, thanks, I'll take a look.

**Comment by d4rkr00t** [comment] 2015-10-17 07:04
Could you just try to remove and install package again? Because I can't reproduce this problem.

**Comment by d4rkr00t** [comment] 2015-10-17 08:46
Ok, a reproduced it. I think it might be some kind of cache in atom, just reload atom is enough to fix this issue :)

**Comment by d4rkr00t** [comment] 2015-10-25 10:27
Does it still an issue or i can close this one?

**Closed as completed** 2015-10-26 01:21 UTC
